import LoadableComponent from './../Loadable/index';
import { ClaimsIcon, ClaimsSelectIcon, ConvertIcon, ConvertSelectIcon,  UnStakeIcon, UnStakeSelectIcon } from '../icons/StakeIcon';
export const userRouter: any = [
  {
    path: '/user',
    name: 'user',
    title: 'User',
    component: LoadableComponent(() => import('../../components/Layout/UserLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/stake',
    name: 'stake',
    permission: '',
    title: 'Stake',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Stake/stake')),
  },
];

export const appRouters: any = [
  {
    path: '/layout',
    name: 'home',
    title: 'Home',
    component: LoadableComponent(() => import('../../components/Layout/AppLayout')),
    isLayout: true,
    showInMenu: true,
  },
  // {
  //   path: '/dashboard',
  //   name: 'dashboard',
  //   permission: '',
  //   title: 'Dashboard',
  //   icon: StakeIcon,
  //   iconSelect: StakeSelectIcon,
  //   showInMenu: false,
  //   component: LoadableComponent(() => import('../../scenes/Dashboard/dashboard')),
  // },
  // {
  //   path: '/stake',
  //   name: 'stake',
  //   permission: '',
  //   title: 'Stake',
  //   icon: StakeIcon,
  //   iconSelect: StakeSelectIcon,
  //   showInMenu: true,
  //   component: LoadableComponent(() => import('../../scenes/Stake/stake')),
  // },
  {
    path: '/stake',
    name: 'stake',
    permission: '',
    title: 'Stake',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Stake/stake')),
  },
  {
    path: '/unstake',
    name: 'unstake',
    permission: '',
    title: 'Unstake',
    icon: UnStakeIcon,
    iconSelect: UnStakeSelectIcon,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Unstake/unstake')),
  },
  {
    path: '/claims',
    name: 'claim',
    permission: '',
    title: 'Claim',
    icon: ClaimsIcon,
    iconSelect: ClaimsSelectIcon,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Claims/claims')),
  },
  {
    path: '/convert',
    name: 'convert',
    permission: '',
    title: 'Convert',
    icon: ConvertIcon,
    iconSelect: ConvertSelectIcon,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Convert/convert')),
  },
  {
    path: '/"',
    name: 'main',
    permission: '',
    title: 'Main',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Main/mains')),
  },
  // {
  //   path: '/page',
  //   name: 'page',
  //   permission: '',
  //   title: 'Page',
  //   showInMenu: false,
  //   component: LoadableComponent(() => import('../../scenes/Main/otherPage')),
  // },
  {
    path: '/logout',
    permission: '',
    title: 'Logout',
    name: 'logout',
    showInMenu: false,
    component: LoadableComponent(() => import('../../components/Logout')),
  },
  {
    path: '/exception?:type',
    permission: '',
    title: 'exception',
    name: 'exception',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Exception')),
  },
];

export const routers = [...appRouters,...userRouter];
